[package]
name = "FlashID2Chinese"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_Console", "Win32_Foundation"] }

[build-dependencies]
anyhow = "1.0"
